"$schema" = "https://starship.rs/config-schema.json"

# Palette inline via hex (optional: define palettes to name them)
# c1 = #C6C3CE, c2 = #444859, c3 = #E0DEF4, c4 = #CBA6F7, c5 = #F38BA8

add_newline = false

format = """[╭─](fg:#CBA6F7)\
[](#444859)\
$os\
$shell\
[](fg:#444859 bg:#C6C3CE)\
$username$hostname\
[](fg:#C6C3CE bg:#E0DEF4)\
$directory\
$git_branch$git_status\
[](fg:#E0DEF4 bg:#CBA6F7)\
$cmd_duration\
[](fg:#CBA6F7)\
\n\
[╰─](fg:#CBA6F7) $status"""

right_format = """[](#E0DEF4)\
$nodejs$python$java$rust$php\
[](fg:#E0DEF4 bg:#C6C3CE)\
$time\
[](fg:#C6C3CE)"""

# OS icon matching OMP os segment
[os]
disabled = false
style = "bg:#444859 fg:#E0DEF4"
format = "[$symbol]($style)"

[os.symbols]
Arch = " "    # Arch Linux
NixOS = " "   # NixOS (common Nerd Font glyph)
Linux = " "   # Fallback for other Linux distros
Macos = " "
Windows = " "
Ubuntu = " "  # optional, if you hop distros
Debian = " "  # optional

# Shell segment with icons
[shell]
disabled = false
style = "bg:#444859 fg:#E0DEF4"
bash_indicator = ""
fish_indicator = ""
zsh_indicator = ""
unknown_indicator = ""
format = "[$indicator]($style)"

# Username and hostname combined like "user:host" on c1 background
[username]
show_always = true
style_user = "bg:#C6C3CE fg:#444859"
style_root = "bg:#C6C3CE fg:#444859"
format = "[ $user]($style)"

[hostname]
ssh_only = false
style = "bg:#C6C3CE fg:#444859"
format = "[:$hostname ]($style)"

# Path on c3 with dark fg; like OMP "  <path>"
[directory]
style = "bg:#E0DEF4 fg:#444859"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Git: branch + status on c3
[git_branch]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
format = "[ | $symbol $branch ]($style)"

[git_status]
style = "bg:#E0DEF4 fg:#444859"
format = '[$all_status$ahead_behind ]($style)'

# Execution time on c4, diamond-like closure
[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bg:#CBA6F7 fg:#444859"
format = "[  $duration ]($style)"

# Status arrow like OMP, always visible
[status]
disabled = false
symbol = ""
success_symbol = ""
format = "$symbol "

# Right: language/tooling modules shown by context
[nodejs]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
format = "[ $symbol ($version) ]($style)"
detect_extensions = ["js", "mjs", "cjs", "ts", "jsx", "tsx"]
detect_files = ["package.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb"]

[python]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
# Show venv name (if any) and major version similar to OMP
# Starship exposes $version; extracting Major only is not built-in,
# but we can keep full version or trim using a custom command (optional).
format = "[ $symbol ($version)($virtualenv ) ]($style)"
# If you want only major version, consider a custom module.

[java]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
format = "[ $symbol ($version) ]($style)"

[php]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
# Starship gives full version; minor trimming requires custom script.
format = "[ $symbol ($version) ]($style)"

[aws]
symbol = ""
style = "bg:#E0DEF4 fg:#444859"
format = "[ $symbol $profile($region ) ]($style)"

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:#C6C3CE fg:#444859"
format = "[  $time ]($style)"
